// GENERATED by tools/build_art.py — do not edit by hand.
CG.DATA.art = {
 "images": {
  "bullet": "assets/atlas/bullet.png",
  "flash": "assets/atlas/flash.png",
  "pk_rapid": "assets/atlas/pk_rapid.png",
  "pk_barrier": "assets/atlas/pk_barrier.png",
  "pk_life": "assets/atlas/pk_life.png",
  "e_flyer": "assets/atlas/e_flyer.png",
  "e_turret": "assets/atlas/e_turret.png",
  "e_barrel": "assets/atlas/e_barrel.png",
  "e_wreck": "assets/atlas/e_wreck.png",
  "boss_cannon": "assets/atlas/boss_cannon.png",
  "boss_barrel": "assets/atlas/boss_barrel.png",
  "boss_core": "assets/atlas/boss_core.png",
  "boss_core_dmg": "assets/atlas/boss_core_dmg.png",
  "boss_core_dead": "assets/atlas/boss_core_dead.png",
  "ebullet": "assets/atlas/ebullet.png",
  "prop_fern": "assets/atlas/prop_fern.png",
  "prop_rock": "assets/atlas/prop_rock.png",
  "prop_crate": "assets/atlas/prop_crate.png",
  "ledge_jungle": "assets/atlas/ledge_jungle.png",
  "g_top_jungle": "assets/atlas/g_top_jungle.png",
  "g_top_jungle_1": "assets/atlas/g_top_jungle_1.png",
  "g_top_jungle_2": "assets/atlas/g_top_jungle_2.png",
  "g_in_jungle": "assets/atlas/g_in_jungle.png",
  "g_in_jungle_1": "assets/atlas/g_in_jungle_1.png",
  "g_left_jungle": "assets/atlas/g_left_jungle.png",
  "g_right_jungle": "assets/atlas/g_right_jungle.png",
  "water_jungle": "assets/atlas/water_jungle.png",
  "water_deep_jungle": "assets/atlas/water_deep_jungle.png",
  "boss_wall": "assets/atlas/boss_wall.png",
  "g_top_base": "assets/atlas/g_top_base.png",
  "g_top_base_1": "assets/atlas/g_top_base_1.png",
  "g_top_base_2": "assets/atlas/g_top_base_2.png",
  "g_in_base": "assets/atlas/g_in_base.png",
  "g_in_base_1": "assets/atlas/g_in_base_1.png",
  "g_left_base": "assets/atlas/g_left_base.png",
  "g_right_base": "assets/atlas/g_right_base.png",
  "water_base": "assets/atlas/water_base.png",
  "water_deep_base": "assets/atlas/water_deep_base.png",
  "wall_base": "assets/atlas/wall_base.png",
  "g_top_snow": "assets/atlas/g_top_snow.png",
  "g_top_snow_1": "assets/atlas/g_top_snow_1.png",
  "g_top_snow_2": "assets/atlas/g_top_snow_2.png",
  "g_in_snow": "assets/atlas/g_in_snow.png",
  "g_in_snow_1": "assets/atlas/g_in_snow_1.png",
  "water_snow": "assets/atlas/water_snow.png",
  "water_deep_snow": "assets/atlas/water_deep_snow.png",
  "wall_snow": "assets/atlas/wall_snow.png",
  "ledge_base": "assets/atlas/ledge_base.png",
  "ledge_snow": "assets/atlas/ledge_snow.png",
  "prop_11": "assets/atlas/prop_11.png",
  "prop_12": "assets/atlas/prop_12.png",
  "prop_13": "assets/atlas/prop_13.png",
  "prop_14": "assets/atlas/prop_14.png",
  "prop_15": "assets/atlas/prop_15.png",
  "prop_16": "assets/atlas/prop_16.png",
  "prop_17": "assets/atlas/prop_17.png",
  "prop_18": "assets/atlas/prop_18.png",
  "prop_19": "assets/atlas/prop_19.png",
  "prop_31": "assets/atlas/prop_31.png",
  "prop_32": "assets/atlas/prop_32.png",
  "prop_33": "assets/atlas/prop_33.png",
  "prop_34": "assets/atlas/prop_34.png",
  "prop_35": "assets/atlas/prop_35.png",
  "prop_36": "assets/atlas/prop_36.png",
  "prop_37": "assets/atlas/prop_37.png",
  "prop_38": "assets/atlas/prop_38.png",
  "prop_39": "assets/atlas/prop_39.png",
  "prop_40": "assets/atlas/prop_40.png",
  "prop_41": "assets/atlas/prop_41.png",
  "prop_43": "assets/atlas/prop_43.png",
  "prop_45": "assets/atlas/prop_45.png",
  "prop_46": "assets/atlas/prop_46.png",
  "prop_47": "assets/atlas/prop_47.png",
  "prop_48": "assets/atlas/prop_48.png",
  "portrait_razor": "assets/atlas/portrait_razor.png",
  "portrait_nova": "assets/atlas/portrait_nova.png",
  "portrait_kite": "assets/atlas/portrait_kite.png",
  "portrait_brick": "assets/atlas/portrait_brick.png",
  "portrait_volt": "assets/atlas/portrait_volt.png",
  "portrait_razor_off": "assets/atlas/portrait_razor_off.png",
  "portrait_nova_off": "assets/atlas/portrait_nova_off.png",
  "portrait_kite_off": "assets/atlas/portrait_kite_off.png",
  "portrait_brick_off": "assets/atlas/portrait_brick_off.png",
  "portrait_volt_off": "assets/atlas/portrait_volt_off.png",
  "ab_razor": "assets/atlas/ab_razor.png",
  "ab_nova": "assets/atlas/ab_nova.png",
  "ab_kite": "assets/atlas/ab_kite.png",
  "ab_brick": "assets/atlas/ab_brick.png",
  "ab_volt": "assets/atlas/ab_volt.png",
  "ab_razor_off": "assets/atlas/ab_razor_off.png",
  "ab_nova_off": "assets/atlas/ab_nova_off.png",
  "ab_kite_off": "assets/atlas/ab_kite_off.png",
  "ab_brick_off": "assets/atlas/ab_brick_off.png",
  "ab_volt_off": "assets/atlas/ab_volt_off.png",
  "pk_heal": "assets/atlas/pk_heal.png",
  "pk_heal_big": "assets/atlas/pk_heal_big.png",
  "pk_teamlife": "assets/atlas/pk_teamlife.png",
  "pk_spread": "assets/atlas/pk_spread.png",
  "pk_ammo": "assets/atlas/pk_ammo.png",
  "flare": "assets/atlas/flare.png",
  "hud_heart": "assets/atlas/hud_heart.png",
  "hud_heart_empty": "assets/atlas/hud_heart_empty.png",
  "life": "assets/atlas/life.png",
  "hud_skull": "assets/atlas/hud_skull.png",
  "hud_crown": "assets/atlas/hud_crown.png",
  "dot_0": "assets/atlas/dot_0.png",
  "dot_1": "assets/atlas/dot_1.png",
  "dot_2": "assets/atlas/dot_2.png",
  "dot_3": "assets/atlas/dot_3.png",
  "dot_4": "assets/atlas/dot_4.png",
  "ic_friends": "assets/atlas/ic_friends.png",
  "ic_party": "assets/atlas/ic_party.png",
  "ic_queue": "assets/atlas/ic_queue.png",
  "ic_invite": "assets/atlas/ic_invite.png",
  "ic_settings": "assets/atlas/ic_settings.png",
  "ic_admin": "assets/atlas/ic_admin.png",
  "ic_bot": "assets/atlas/ic_bot.png",
  "ic_key": "assets/atlas/ic_key.png",
  "ic_trophy": "assets/atlas/ic_trophy.png",
  "ic_exit": "assets/atlas/ic_exit.png",
  "bgp_sky_jungle": "assets/atlas/bgp_sky_jungle.png",
  "bgp_sky_base": "assets/atlas/bgp_sky_base.png",
  "bgp_far_base": "assets/atlas/bgp_far_base.png",
  "bgp_near_base": "assets/atlas/bgp_near_base.png",
  "bgp_sky_snow": "assets/atlas/bgp_sky_snow.png",
  "bgp_near_snow": "assets/atlas/bgp_near_snow.png",
  "bg15_1": "assets/atlas/bg15_1.png",
  "bg15_2": "assets/atlas/bg15_2.png",
  "bg15_3": "assets/atlas/bg15_3.png",
  "bg15_4": "assets/atlas/bg15_4.png",
  "bg15_5": "assets/atlas/bg15_5.png",
  "bg15_6": "assets/atlas/bg15_6.png",
  "bg15_7": "assets/atlas/bg15_7.png",
  "bg15_8": "assets/atlas/bg15_8.png",
  "bg15_9": "assets/atlas/bg15_9.png",
  "bg15_10": "assets/atlas/bg15_10.png",
  "bg15_11": "assets/atlas/bg15_11.png",
  "bg15_12": "assets/atlas/bg15_12.png",
  "bg15_13": "assets/atlas/bg15_13.png",
  "bg15_14": "assets/atlas/bg15_14.png",
  "bg15_15": "assets/atlas/bg15_15.png",
  "cv50_0": "assets/atlas/cv50_0.png",
  "cv50_1": "assets/atlas/cv50_1.png",
  "cv50_2": "assets/atlas/cv50_2.png",
  "cv50_3": "assets/atlas/cv50_3.png",
  "cv50_4": "assets/atlas/cv50_4.png",
  "cv50_5": "assets/atlas/cv50_5.png",
  "cv50_6": "assets/atlas/cv50_6.png",
  "cv50_7": "assets/atlas/cv50_7.png",
  "cv50_8": "assets/atlas/cv50_8.png",
  "cv50_9": "assets/atlas/cv50_9.png",
  "cv50_11": "assets/atlas/cv50_11.png",
  "cv50_12": "assets/atlas/cv50_12.png",
  "cv50_13": "assets/atlas/cv50_13.png",
  "cv50_14": "assets/atlas/cv50_14.png",
  "cv50_15": "assets/atlas/cv50_15.png",
  "cv50_16": "assets/atlas/cv50_16.png",
  "cv50_17": "assets/atlas/cv50_17.png",
  "cv50_18": "assets/atlas/cv50_18.png",
  "cv50_19": "assets/atlas/cv50_19.png",
  "cv50_20": "assets/atlas/cv50_20.png",
  "cv50_21": "assets/atlas/cv50_21.png",
  "cv50_22": "assets/atlas/cv50_22.png",
  "cv50_23": "assets/atlas/cv50_23.png",
  "cv50_24": "assets/atlas/cv50_24.png",
  "cv50_25": "assets/atlas/cv50_25.png",
  "cv50_26": "assets/atlas/cv50_26.png",
  "cv50_27": "assets/atlas/cv50_27.png",
  "cv50_28": "assets/atlas/cv50_28.png",
  "cv50_29": "assets/atlas/cv50_29.png",
  "cv50_30": "assets/atlas/cv50_30.png",
  "cv50_31": "assets/atlas/cv50_31.png",
  "cv50_32": "assets/atlas/cv50_32.png",
  "cv50_33": "assets/atlas/cv50_33.png",
  "cv50_34": "assets/atlas/cv50_34.png",
  "cv50_35": "assets/atlas/cv50_35.png",
  "cv50_36": "assets/atlas/cv50_36.png",
  "cv50_37": "assets/atlas/cv50_37.png",
  "cv50_38": "assets/atlas/cv50_38.png",
  "cv50_39": "assets/atlas/cv50_39.png",
  "cv50_40": "assets/atlas/cv50_40.png",
  "cv50_41": "assets/atlas/cv50_41.png",
  "cv50_42": "assets/atlas/cv50_42.png",
  "cv50_43": "assets/atlas/cv50_43.png",
  "cv50_44": "assets/atlas/cv50_44.png",
  "cv50_45": "assets/atlas/cv50_45.png",
  "cv50_46": "assets/atlas/cv50_46.png",
  "cv50_47": "assets/atlas/cv50_47.png",
  "cv50_48": "assets/atlas/cv50_48.png",
  "cv50_49": "assets/atlas/cv50_49.png",
  "pk_pierce": "assets/atlas/pk_pierce.png",
  "pk_blast": "assets/atlas/pk_blast.png",
  "pk_double": "assets/atlas/pk_double.png",
  "pk_ice": "assets/atlas/pk_ice.png",
  "pk_fire": "assets/atlas/pk_fire.png",
  "pk_shock": "assets/atlas/pk_shock.png",
  "pk_magnet": "assets/atlas/pk_magnet.png",
  "pk_slowmo": "assets/atlas/pk_slowmo.png",
  "pk_boots": "assets/atlas/pk_boots.png",
  "pk_bigheal": "assets/atlas/pk_bigheal.png",
  "ab_ghost": "assets/atlas/ab_ghost.png",
  "ab_hammer": "assets/atlas/ab_hammer.png",
  "ab_viper": "assets/atlas/ab_viper.png",
  "ab_atlas": "assets/atlas/ab_atlas.png",
  "pk_autoaim": "assets/atlas/pk_autoaim.png",
  "pk_longer": "assets/atlas/pk_longer.png",
  "pk_armor": "assets/atlas/pk_armor.png",
  "pk_dcoins": "assets/atlas/pk_dcoins.png",
  "pk_danger": "assets/atlas/pk_danger.png",
  "rank_bronze_1": "assets/atlas/rank_bronze_1.png",
  "rank_bronze_2": "assets/atlas/rank_bronze_2.png",
  "rank_bronze_3": "assets/atlas/rank_bronze_3.png",
  "rank_silver_1": "assets/atlas/rank_silver_1.png",
  "rank_silver_2": "assets/atlas/rank_silver_2.png",
  "rank_silver_3": "assets/atlas/rank_silver_3.png",
  "rank_gold_1": "assets/atlas/rank_gold_1.png",
  "rank_gold_2": "assets/atlas/rank_gold_2.png",
  "rank_gold_3": "assets/atlas/rank_gold_3.png",
  "rank_platinum_1": "assets/atlas/rank_platinum_1.png",
  "rank_platinum_2": "assets/atlas/rank_platinum_2.png",
  "rank_platinum_3": "assets/atlas/rank_platinum_3.png",
  "rank_diamond_1": "assets/atlas/rank_diamond_1.png",
  "rank_diamond_2": "assets/atlas/rank_diamond_2.png",
  "rank_diamond_3": "assets/atlas/rank_diamond_3.png",
  "rank_master_1": "assets/atlas/rank_master_1.png",
  "rank_master_2": "assets/atlas/rank_master_2.png",
  "rank_master_3": "assets/atlas/rank_master_3.png",
  "rank_legend": "assets/atlas/rank_legend.png",
  "e_gate": "assets/atlas/e_gate.png",
  "e_mouth": "assets/atlas/e_mouth.png",
  "rock": "assets/atlas/rock.png",
  "boss_statue": "assets/atlas/boss_statue.png",
  "e_orb": "assets/atlas/e_orb.png",
  "fireball": "assets/atlas/fireball.png",
  "e_disc": "assets/atlas/e_disc.png",
  "hz_nozzle": "assets/atlas/hz_nozzle.png",
  "hz_crusher": "assets/atlas/hz_crusher.png",
  "banner_steel": "assets/atlas/banner_steel.png",
  "banner_jungle": "assets/atlas/banner_jungle.png",
  "banner_inferno": "assets/atlas/banner_inferno.png",
  "banner_arctic": "assets/atlas/banner_arctic.png",
  "banner_neon": "assets/atlas/banner_neon.png",
  "banner_carbon": "assets/atlas/banner_carbon.png",
  "banner_bloodmoon": "assets/atlas/banner_bloodmoon.png",
  "banner_gold": "assets/atlas/banner_gold.png",
  "banner_legend": "assets/atlas/banner_legend.png",
  "g_top_w_jungle": "assets/atlas/g_top_w_jungle.png",
  "g_top_w_jungle_1": "assets/atlas/g_top_w_jungle_1.png",
  "g_in_w_jungle": "assets/atlas/g_in_w_jungle.png",
  "g_in_w_jungle_1": "assets/atlas/g_in_w_jungle_1.png",
  "ledge_w_jungle": "assets/atlas/ledge_w_jungle.png",
  "water_w_jungle": "assets/atlas/water_w_jungle.png",
  "g_top_w_base1": "assets/atlas/g_top_w_base1.png",
  "g_top_w_base1_1": "assets/atlas/g_top_w_base1_1.png",
  "g_in_w_base1": "assets/atlas/g_in_w_base1.png",
  "g_in_w_base1_1": "assets/atlas/g_in_w_base1_1.png",
  "ledge_w_base1": "assets/atlas/ledge_w_base1.png",
  "water_w_base1": "assets/atlas/water_w_base1.png",
  "g_top_w_falls": "assets/atlas/g_top_w_falls.png",
  "g_top_w_falls_1": "assets/atlas/g_top_w_falls_1.png",
  "g_in_w_falls": "assets/atlas/g_in_w_falls.png",
  "g_in_w_falls_1": "assets/atlas/g_in_w_falls_1.png",
  "ledge_w_falls": "assets/atlas/ledge_w_falls.png",
  "water_w_falls": "assets/atlas/water_w_falls.png",
  "g_top_w_base2": "assets/atlas/g_top_w_base2.png",
  "g_top_w_base2_1": "assets/atlas/g_top_w_base2_1.png",
  "g_in_w_base2": "assets/atlas/g_in_w_base2.png",
  "g_in_w_base2_1": "assets/atlas/g_in_w_base2_1.png",
  "ledge_w_base2": "assets/atlas/ledge_w_base2.png",
  "water_w_base2": "assets/atlas/water_w_base2.png",
  "g_top_w_snow": "assets/atlas/g_top_w_snow.png",
  "g_top_w_snow_1": "assets/atlas/g_top_w_snow_1.png",
  "g_in_w_snow": "assets/atlas/g_in_w_snow.png",
  "g_in_w_snow_1": "assets/atlas/g_in_w_snow_1.png",
  "ledge_w_snow": "assets/atlas/ledge_w_snow.png",
  "water_w_snow": "assets/atlas/water_w_snow.png",
  "g_top_w_energy": "assets/atlas/g_top_w_energy.png",
  "g_top_w_energy_1": "assets/atlas/g_top_w_energy_1.png",
  "g_in_w_energy": "assets/atlas/g_in_w_energy.png",
  "g_in_w_energy_1": "assets/atlas/g_in_w_energy_1.png",
  "ledge_w_energy": "assets/atlas/ledge_w_energy.png",
  "water_w_energy": "assets/atlas/water_w_energy.png",
  "g_top_w_hangar": "assets/atlas/g_top_w_hangar.png",
  "g_top_w_hangar_1": "assets/atlas/g_top_w_hangar_1.png",
  "g_in_w_hangar": "assets/atlas/g_in_w_hangar.png",
  "g_in_w_hangar_1": "assets/atlas/g_in_w_hangar_1.png",
  "ledge_w_hangar": "assets/atlas/ledge_w_hangar.png",
  "water_w_hangar": "assets/atlas/water_w_hangar.png",
  "g_top_w_alien": "assets/atlas/g_top_w_alien.png",
  "g_top_w_alien_1": "assets/atlas/g_top_w_alien_1.png",
  "g_in_w_alien": "assets/atlas/g_in_w_alien.png",
  "g_in_w_alien_1": "assets/atlas/g_in_w_alien_1.png",
  "ledge_w_alien": "assets/atlas/ledge_w_alien.png",
  "water_w_alien": "assets/atlas/water_w_alien.png",
  "boss_wall_w_jungle": "assets/atlas/boss_wall_w_jungle.png",
  "boss_cannon_w_jungle": "assets/atlas/boss_cannon_w_jungle.png",
  "boss_barrel_w_jungle": "assets/atlas/boss_barrel_w_jungle.png",
  "boss_core_w_jungle": "assets/atlas/boss_core_w_jungle.png",
  "boss_core_dmg_w_jungle": "assets/atlas/boss_core_dmg_w_jungle.png",
  "boss_core_dead_w_jungle": "assets/atlas/boss_core_dead_w_jungle.png",
  "boss_wall_w_base1": "assets/atlas/boss_wall_w_base1.png",
  "boss_cannon_w_base1": "assets/atlas/boss_cannon_w_base1.png",
  "boss_barrel_w_base1": "assets/atlas/boss_barrel_w_base1.png",
  "boss_core_w_base1": "assets/atlas/boss_core_w_base1.png",
  "boss_core_dmg_w_base1": "assets/atlas/boss_core_dmg_w_base1.png",
  "boss_core_dead_w_base1": "assets/atlas/boss_core_dead_w_base1.png",
  "boss_wall_w_base2": "assets/atlas/boss_wall_w_base2.png",
  "boss_cannon_w_base2": "assets/atlas/boss_cannon_w_base2.png",
  "boss_barrel_w_base2": "assets/atlas/boss_barrel_w_base2.png",
  "boss_core_w_base2": "assets/atlas/boss_core_w_base2.png",
  "boss_core_dmg_w_base2": "assets/atlas/boss_core_dmg_w_base2.png",
  "boss_core_dead_w_base2": "assets/atlas/boss_core_dead_w_base2.png",
  "boss_wall_w_hangar": "assets/atlas/boss_wall_w_hangar.png",
  "boss_cannon_w_hangar": "assets/atlas/boss_cannon_w_hangar.png",
  "boss_barrel_w_hangar": "assets/atlas/boss_barrel_w_hangar.png",
  "boss_core_w_hangar": "assets/atlas/boss_core_w_hangar.png",
  "boss_core_dmg_w_hangar": "assets/atlas/boss_core_dmg_w_hangar.png",
  "boss_core_dead_w_hangar": "assets/atlas/boss_core_dead_w_hangar.png",
  "boss_tank": "assets/atlas/boss_tank.png",
  "bomb": "assets/atlas/bomb.png",
  "pk_coin": "assets/atlas/pk_coin.png",
  "ab_jax": "assets/atlas/ab_jax.png",
  "ab_duke": "assets/atlas/ab_duke.png",
  "px_sentry": "assets/atlas/px_sentry.png",
  "pk_overdrive": "assets/atlas/pk_overdrive.png",
  "hook_open": "assets/atlas/hook_open.png",
  "hook_closed": "assets/atlas/hook_closed.png",
  "rope_piece": "assets/atlas/rope_piece.png",
  "rope_coil": "assets/atlas/rope_coil.png",
  "fx_grab_1": "assets/atlas/fx_grab_1.png",
  "fx_grab_2": "assets/atlas/fx_grab_2.png"
 },
 "sheets": {
  "commandos": {
   "path": "assets/atlas/commandos.png",
   "fw": 288,
   "fh": 288
  },
  "sheet_runner": {
   "path": "assets/atlas/sheet_runner.png",
   "fw": 208,
   "fh": 200
  },
  "sheet_rifle": {
   "path": "assets/atlas/sheet_rifle.png",
   "fw": 224,
   "fh": 200
  },
  "fx_boom": {
   "path": "assets/atlas/fx_boom.png",
   "fw": 165,
   "fh": 163
  },
  "fx_splash": {
   "path": "assets/atlas/fx_splash.png",
   "fw": 134,
   "fh": 168
  },
  "agents": {
   "path": "assets/atlas/agents.png",
   "fw": 288,
   "fh": 288
  },
  "fx_storm": {
   "path": "assets/atlas/fx_storm.png",
   "fw": 156,
   "fh": 127
  },
  "fx_tracer": {
   "path": "assets/atlas/fx_tracer.png",
   "fw": 195,
   "fh": 38
  },
  "fx_shells": {
   "path": "assets/atlas/fx_shells.png",
   "fw": 233,
   "fh": 98
  },
  "fx_mend": {
   "path": "assets/atlas/fx_mend.png",
   "fw": 156,
   "fh": 135
  },
  "fx_plus": {
   "path": "assets/atlas/fx_plus.png",
   "fw": 89,
   "fh": 131
  },
  "fx_dash": {
   "path": "assets/atlas/fx_dash.png",
   "fw": 180,
   "fh": 84
  },
  "fx_blink": {
   "path": "assets/atlas/fx_blink.png",
   "fw": 230,
   "fh": 134
  },
  "fx_slash": {
   "path": "assets/atlas/fx_slash.png",
   "fw": 197,
   "fh": 90
  },
  "fx_dome": {
   "path": "assets/atlas/fx_dome.png",
   "fw": 240,
   "fh": 117
  },
  "fx_dome_break": {
   "path": "assets/atlas/fx_dome_break.png",
   "fw": 208,
   "fh": 122
  },
  "fx_arc": {
   "path": "assets/atlas/fx_arc.png",
   "fw": 206,
   "fh": 94
  },
  "fx_spark": {
   "path": "assets/atlas/fx_spark.png",
   "fw": 159,
   "fh": 127
  },
  "fx_charge": {
   "path": "assets/atlas/fx_charge.png",
   "fw": 93,
   "fh": 99
  },
  "e_bug": {
   "path": "assets/atlas/e_bug.png",
   "fw": 246,
   "fh": 180
  },
  "boss_giant": {
   "path": "assets/atlas/boss_giant.png",
   "fw": 228,
   "fh": 287
  },
  "boss_heart": {
   "path": "assets/atlas/boss_heart.png",
   "fw": 193,
   "fh": 274
  },
  "hz_flame": {
   "path": "assets/atlas/hz_flame.png",
   "fw": 96,
   "fh": 175
  },
  "boss_heli": {
   "path": "assets/atlas/boss_heli.png",
   "fw": 356,
   "fh": 206
  },
  "px_gren": {
   "path": "assets/atlas/px_gren.png",
   "fw": 219,
   "fh": 272
  },
  "px_drone": {
   "path": "assets/atlas/px_drone.png",
   "fw": 307,
   "fh": 153
  }
 },
 "scale": {
  "bullet": 0.4554,
  "flash": 0.8824,
  "pk_rapid": 0.5122,
  "pk_barrier": 0.5185,
  "pk_life": 0.5149,
  "e_flyer": 0.6667,
  "fx_boom": 0.5818,
  "fx_splash": 1.1194,
  "e_turret": 0.7467,
  "e_barrel": 0.6131,
  "e_wreck": 0.7453,
  "boss_cannon": 0.9667,
  "boss_barrel": 0.7778,
  "boss_core": 0.8516,
  "boss_core_dmg": 0.9041,
  "boss_core_dead": 0.9296,
  "ebullet": 0.7317,
  "prop_fern": 0.7742,
  "prop_rock": 0.6842,
  "prop_crate": 0.6562,
  "prop_11": 0.7285,
  "prop_12": 0.6957,
  "prop_13": 0.7921,
  "prop_14": 0.8982,
  "prop_15": 0.7692,
  "prop_16": 1.2429,
  "prop_17": 0.8889,
  "prop_18": 0.8594,
  "prop_19": 0.7299,
  "prop_31": 1.2258,
  "prop_32": 0.7742,
  "prop_33": 0.7377,
  "prop_34": 0.6944,
  "prop_35": 0.5941,
  "prop_36": 0.8911,
  "prop_37": 1.1043,
  "prop_38": 1.1818,
  "prop_39": 0.8421,
  "prop_40": 1.4208,
  "prop_41": 1.1364,
  "prop_43": 1.4365,
  "prop_45": 0.8434,
  "prop_46": 0.7143,
  "prop_47": 0.6306,
  "prop_48": 0.8805,
  "portrait_razor": 1.0,
  "portrait_nova": 1.0,
  "portrait_kite": 1.0,
  "portrait_brick": 1.0,
  "portrait_volt": 1.0,
  "portrait_razor_off": 1.0,
  "portrait_nova_off": 1.0,
  "portrait_kite_off": 1.0,
  "portrait_brick_off": 1.0,
  "portrait_volt_off": 1.0,
  "ab_razor": 0.4238,
  "ab_nova": 0.4267,
  "ab_kite": 0.4183,
  "ab_brick": 0.4103,
  "ab_volt": 0.4156,
  "ab_razor_off": 0.4211,
  "ab_nova_off": 0.4183,
  "ab_kite_off": 0.4238,
  "ab_brick_off": 0.4129,
  "ab_volt_off": 0.4211,
  "pk_heal": 0.4915,
  "pk_heal_big": 0.5241,
  "pk_teamlife": 0.5532,
  "pk_spread": 0.5153,
  "pk_ammo": 0.4861,
  "flare": 0.381,
  "hud_heart": 0.2261,
  "hud_heart_empty": 0.2301,
  "life": 0.3571,
  "hud_skull": 0.3191,
  "hud_crown": 0.2564,
  "dot_0": 1.0,
  "dot_1": 1.0,
  "dot_2": 1.0,
  "dot_3": 1.0,
  "dot_4": 1.0,
  "ic_friends": 1.0,
  "ic_party": 1.0,
  "ic_queue": 1.0,
  "ic_invite": 1.0,
  "ic_settings": 1.0,
  "ic_admin": 1.0,
  "ic_bot": 1.0,
  "ic_key": 1.0,
  "ic_trophy": 1.0,
  "ic_exit": 1.0,
  "cv50_0": 1.0,
  "cv50_1": 1.0,
  "cv50_2": 1.0,
  "cv50_3": 1.0,
  "cv50_4": 1.0,
  "cv50_5": 1.0,
  "cv50_6": 1.0,
  "cv50_7": 1.0,
  "cv50_8": 1.0,
  "cv50_9": 1.0,
  "cv50_11": 1.0,
  "cv50_12": 1.0,
  "cv50_13": 1.0,
  "cv50_14": 1.0,
  "cv50_15": 1.0,
  "cv50_16": 1.0,
  "cv50_17": 1.0,
  "cv50_18": 1.0,
  "cv50_19": 1.0,
  "cv50_20": 1.0,
  "cv50_21": 1.0,
  "cv50_22": 1.0,
  "cv50_23": 1.0,
  "cv50_24": 1.0,
  "cv50_25": 1.0,
  "cv50_26": 1.0,
  "cv50_27": 1.0,
  "cv50_28": 1.0,
  "cv50_29": 1.0,
  "cv50_30": 1.0,
  "cv50_31": 1.0,
  "cv50_32": 1.0,
  "cv50_33": 1.0,
  "cv50_34": 1.0,
  "cv50_35": 1.0,
  "cv50_36": 1.0,
  "cv50_37": 1.0,
  "cv50_38": 1.0,
  "cv50_39": 1.0,
  "cv50_40": 1.0,
  "cv50_41": 1.0,
  "cv50_42": 1.0,
  "cv50_43": 1.0,
  "cv50_44": 1.0,
  "cv50_45": 1.0,
  "cv50_46": 1.0,
  "cv50_47": 1.0,
  "cv50_48": 1.0,
  "cv50_49": 1.0,
  "pk_pierce": 0.4828,
  "pk_blast": 0.5,
  "pk_double": 0.4941,
  "pk_ice": 0.506,
  "pk_fire": 0.497,
  "pk_shock": 0.4855,
  "pk_magnet": 0.497,
  "pk_slowmo": 0.5,
  "pk_boots": 0.4855,
  "pk_bigheal": 0.497,
  "ab_ghost": 0.3787,
  "ab_hammer": 0.3855,
  "ab_viper": 0.3855,
  "ab_atlas": 0.3879,
  "pk_autoaim": 0.2617,
  "pk_longer": 0.5185,
  "pk_armor": 0.5122,
  "pk_dcoins": 0.5185,
  "pk_danger": 0.3889,
  "e_gate": 1.7266,
  "e_mouth": 0.5981,
  "e_bug": 0.2927,
  "rock": 0.3107,
  "boss_statue": 1.2632,
  "e_orb": 0.4158,
  "fireball": 0.2698,
  "e_disc": 0.3265,
  "hz_nozzle": 0.4384,
  "boss_giant": 1.1847,
  "boss_heart": 1.2953,
  "hz_crusher": 0.5251,
  "hz_flame": 0.5,
  "boss_cannon_w_jungle": 0.7643,
  "boss_barrel_w_jungle": 0.641,
  "boss_core_w_jungle": 0.795,
  "boss_core_dmg_w_jungle": 0.795,
  "boss_core_dead_w_jungle": 0.5556,
  "boss_cannon_w_base1": 0.7843,
  "boss_barrel_w_base1": 0.6173,
  "boss_core_w_base1": 0.837,
  "boss_core_dmg_w_base1": 0.837,
  "boss_core_dead_w_base1": 0.5936,
  "boss_cannon_w_base2": 0.6936,
  "boss_barrel_w_base2": 0.625,
  "boss_core_w_base2": 0.9694,
  "boss_core_dmg_w_base2": 0.9596,
  "boss_core_dead_w_base2": 0.65,
  "boss_cannon_w_hangar": 0.7143,
  "boss_barrel_w_hangar": 0.6122,
  "boss_core_w_hangar": 0.8837,
  "boss_core_dmg_w_hangar": 0.8837,
  "boss_core_dead_w_hangar": 0.5991,
  "boss_tank": 0.9322,
  "bomb": 0.219,
  "pk_coin": 0.2339,
  "px_sentry": 0.3243,
  "boss_heli": 0.8427,
  "px_gren": 0.4853,
  "px_drone": 0.2932,
  "pk_overdrive": 0.3243,
  "hook_open": 0.1451,
  "hook_closed": 0.1445,
  "rope_coil": 0.2509,
  "fx_grab_1": 0.4286,
  "fx_grab_2": 0.4573
 },
 "players": [
  {
   "anims": {
    "run_fwd": [
     0,
     5
    ],
    "stand_fwd": [
     6,
     6
    ],
    "stand_up": [
     7,
     7
    ],
    "stand_dup": [
     8,
     8
    ],
    "stand_ddown": [
     9,
     9
    ],
    "run_dup": [
     10,
     12
    ],
    "run_ddown": [
     13,
     14
    ],
    "prone": [
     15,
     15
    ],
    "ball": [
     16,
     17
    ],
    "death": [
     18,
     18
    ]
   },
   "muzzle": {
    "fwd": [
     88,
     -117
    ],
    "up": [
     11,
     -181
    ],
    "dup": [
     81,
     -149
    ],
    "ddown": [
     42,
     -11
    ],
    "prone": [
     115,
     -33
    ]
   }
  },
  {
   "anims": {
    "run_fwd": [
     19,
     24
    ],
    "stand_fwd": [
     25,
     25
    ],
    "stand_up": [
     26,
     26
    ],
    "stand_dup": [
     27,
     27
    ],
    "stand_ddown": [
     28,
     28
    ],
    "run_dup": [
     29,
     31
    ],
    "run_ddown": [
     32,
     33
    ],
    "prone": [
     34,
     34
    ],
    "ball": [
     35,
     36
    ],
    "death": [
     37,
     37
    ]
   },
   "muzzle": {
    "fwd": [
     88,
     -114
    ],
    "up": [
     15,
     -181
    ],
    "dup": [
     80,
     -148
    ],
    "ddown": [
     42,
     -10
    ],
    "prone": [
     113,
     -34
    ]
   }
  }
 ],
 "originY": 0.8333333333333334,
 "playerScale": 0.825,
 "enemyScale": 0.8627,
 "props": {
  "jungle": [
   "prop_fern",
   "prop_rock",
   "prop_crate",
   "prop_40",
   "prop_41",
   "prop_43",
   "prop_45",
   "prop_46",
   "prop_47",
   "prop_48"
  ],
  "base": [
   "prop_11",
   "prop_12",
   "prop_13",
   "prop_14",
   "prop_15",
   "prop_16",
   "prop_17",
   "prop_18",
   "prop_19"
  ],
  "snow": [
   "prop_31",
   "prop_32",
   "prop_33",
   "prop_34",
   "prop_35",
   "prop_36",
   "prop_37",
   "prop_38",
   "prop_39"
  ]
 },
 "agents": {
  "razor": {
   "anims": {
    "run_fwd": [
     0,
     5,
     1.0
    ],
    "stand_fwd": [
     6,
     6,
     1.0
    ],
    "stand_up": [
     7,
     7,
     1.0
    ],
    "stand_dup": [
     8,
     8,
     1.0
    ],
    "stand_ddown": [
     9,
     9,
     1.0
    ],
    "run_dup": [
     10,
     12,
     1.0
    ],
    "run_ddown": [
     13,
     15,
     1.0
    ],
    "prone": [
     16,
     16,
     1.0
    ],
    "ball": [
     17,
     18,
     1.0
    ],
    "death": [
     19,
     19,
     1.0
    ]
   },
   "muzzle": {
    "fwd": [
     47,
     -83
    ],
    "up": [
     -6,
     -149
    ],
    "dup": [
     63,
     -123
    ],
    "ddown": [
     41,
     -10
    ],
    "prone": [
     56,
     -23
    ]
   },
   "spin": false,
   "partial": false
  },
  "nova": {
   "anims": {
    "run_fwd": [
     20,
     25,
     1.0
    ],
    "stand_fwd": [
     26,
     26,
     1.0
    ],
    "stand_up": [
     27,
     27,
     1.0
    ],
    "stand_dup": [
     28,
     28,
     1.0
    ],
    "stand_ddown": [
     29,
     29,
     1.0
    ],
    "run_dup": [
     30,
     32,
     1.0
    ],
    "run_ddown": [
     33,
     35,
     1.0
    ],
    "prone": [
     36,
     36,
     1.0
    ],
    "ball": [
     37,
     38,
     1.0
    ],
    "death": [
     39,
     39,
     1.0
    ]
   },
   "muzzle": {
    "fwd": [
     47,
     -86
    ],
    "up": [
     -9,
     -151
    ],
    "dup": [
     63,
     -129
    ],
    "ddown": [
     44,
     -8
    ],
    "prone": [
     54,
     -24
    ]
   },
   "spin": false,
   "partial": false
  },
  "kite": {
   "anims": {
    "run_fwd": [
     40,
     45,
     1.0
    ],
    "stand_fwd": [
     46,
     46,
     1.0
    ],
    "stand_up": [
     47,
     47,
     1.0
    ],
    "stand_dup": [
     48,
     48,
     1.0
    ],
    "stand_ddown": [
     49,
     49,
     1.0
    ],
    "run_dup": [
     50,
     52,
     0.6324
    ],
    "run_ddown": [
     53,
     55,
     0.6324
    ],
    "prone": [
     56,
     56,
     0.6324
    ],
    "ball": [
     57,
     58,
     0.6324
    ],
    "death": [
     59,
     59,
     0.6324
    ]
   },
   "muzzle": {
    "fwd": [
     47,
     -73
    ],
    "up": [
     -5,
     -130
    ],
    "dup": [
     58,
     -129
    ],
    "ddown": [
     30,
     -8
    ],
    "prone": [
     66,
     -27
    ]
   },
   "spin": false,
   "partial": false
  },
  "brick": {
   "anims": {
    "run_fwd": [
     60,
     65,
     1.0
    ],
    "stand_fwd": [
     66,
     66,
     1.0
    ],
    "stand_up": [
     67,
     67,
     1.0
    ],
    "stand_dup": [
     68,
     68,
     1.0
    ],
    "stand_ddown": [
     69,
     69,
     1.0
    ],
    "run_dup": [
     70,
     72,
     1.0
    ],
    "run_ddown": [
     73,
     75,
     1.0
    ],
    "prone": [
     76,
     76,
     1.0
    ],
    "ball": [
     77,
     78,
     1.0
    ],
    "death": [
     79,
     79,
     1.0
    ]
   },
   "muzzle": {
    "fwd": [
     43,
     -69
    ],
    "up": [
     -19,
     -123
    ],
    "dup": [
     61,
     -118
    ],
    "ddown": [
     52,
     -7
    ],
    "prone": [
     60,
     -26
    ]
   },
   "spin": false,
   "partial": false
  },
  "volt": {
   "anims": {
    "run_fwd": [
     80,
     85,
     0.6324
    ],
    "stand_fwd": [
     86,
     86,
     0.6324
    ],
    "stand_up": [
     87,
     87,
     0.6324
    ],
    "stand_dup": [
     88,
     88,
     0.6324
    ],
    "stand_ddown": [
     89,
     89,
     0.6324
    ],
    "run_dup": [
     90,
     92,
     1.0
    ],
    "run_ddown": [
     93,
     95,
     1.0
    ],
    "prone": [
     96,
     96,
     1.0
    ],
    "ball": [
     97,
     98,
     1.0
    ],
    "death": [
     99,
     99,
     1.0
    ]
   },
   "muzzle": {
    "fwd": [
     64,
     -85
    ],
    "up": [
     14,
     -159
    ],
    "dup": [
     63,
     -109
    ],
    "ddown": [
     56,
     -5
    ],
    "prone": [
     52,
     -31
    ]
   },
   "spin": false,
   "partial": false
  },
  "ghost": {
   "anims": {
    "run_fwd": [
     100,
     105,
     0.8944
    ],
    "stand_fwd": [
     106,
     106,
     0.8944
    ],
    "stand_up": [
     107,
     107,
     0.8944
    ],
    "stand_dup": [
     108,
     108,
     0.8944
    ],
    "stand_ddown": [
     109,
     109,
     0.8944
    ],
    "run_dup": [
     110,
     112,
     0.8944
    ],
    "run_ddown": [
     113,
     115,
     0.8944
    ],
    "prone": [
     116,
     116,
     0.8944
    ],
    "ball": [
     117,
     118,
     0.8944
    ],
    "death": [
     119,
     119,
     0.8944
    ]
   },
   "muzzle": {
    "fwd": [
     40,
     -73
    ],
    "up": [
     8,
     -134
    ],
    "dup": [
     64,
     -109
    ],
    "ddown": [
     39,
     -11
    ],
    "prone": [
     64,
     -20
    ]
   },
   "spin": false,
   "partial": false
  },
  "hammer": {
   "anims": {
    "run_fwd": [
     120,
     125,
     0.8944
    ],
    "stand_fwd": [
     126,
     126,
     0.8944
    ],
    "stand_up": [
     127,
     127,
     0.8944
    ],
    "stand_dup": [
     128,
     128,
     0.8944
    ],
    "stand_ddown": [
     129,
     129,
     0.8944
    ],
    "run_dup": [
     130,
     132,
     0.8944
    ],
    "run_ddown": [
     133,
     135,
     0.8944
    ],
    "prone": [
     136,
     136,
     0.8944
    ],
    "ball": [
     137,
     138,
     0.8944
    ],
    "death": [
     139,
     139,
     0.8944
    ]
   },
   "muzzle": {
    "fwd": [
     40,
     -72
    ],
    "up": [
     5,
     -122
    ],
    "dup": [
     58,
     -112
    ],
    "ddown": [
     33,
     -6
    ],
    "prone": [
     62,
     -21
    ]
   },
   "spin": false,
   "partial": false
  },
  "viper": {
   "anims": {
    "run_fwd": [
     140,
     145,
     0.8944
    ],
    "stand_fwd": [
     146,
     146,
     0.8944
    ],
    "stand_up": [
     147,
     147,
     0.8944
    ],
    "stand_dup": [
     148,
     148,
     0.8944
    ],
    "stand_ddown": [
     149,
     149,
     0.8944
    ],
    "run_dup": [
     150,
     152,
     0.8944
    ],
    "run_ddown": [
     153,
     155,
     0.8944
    ],
    "prone": [
     156,
     156,
     0.8944
    ],
    "ball": [
     157,
     158,
     0.8944
    ],
    "death": [
     159,
     159,
     0.8944
    ]
   },
   "muzzle": {
    "fwd": [
     40,
     -69
    ],
    "up": [
     8,
     -122
    ],
    "dup": [
     58,
     -100
    ],
    "ddown": [
     27,
     -8
    ],
    "prone": [
     64,
     -19
    ]
   },
   "spin": false,
   "partial": false
  },
  "atlas": {
   "anims": {
    "run_fwd": [
     160,
     165,
     0.8944
    ],
    "stand_fwd": [
     166,
     166,
     0.8944
    ],
    "stand_up": [
     167,
     167,
     0.8944
    ],
    "stand_dup": [
     168,
     168,
     0.8944
    ],
    "stand_ddown": [
     169,
     169,
     0.8944
    ],
    "run_dup": [
     170,
     172,
     0.8944
    ],
    "run_ddown": [
     173,
     175,
     0.8944
    ],
    "prone": [
     176,
     176,
     0.8944
    ],
    "ball": [
     177,
     177,
     0.8944
    ],
    "death": [
     178,
     178,
     0.8944
    ]
   },
   "muzzle": {
    "fwd": [
     40,
     -67
    ],
    "up": [
     11,
     -114
    ],
    "dup": [
     68,
     -72
    ],
    "ddown": [
     39,
     -8
    ],
    "prone": [
     57,
     -24
    ]
   },
   "spin": true,
   "partial": false
  }
 },
 "agentScale": 1.0687,
 "agentOriginY": 0.8333333333333334,
 "pixel": [
  "agents",
  "portrait_razor",
  "portrait_nova",
  "portrait_kite",
  "portrait_brick",
  "portrait_volt",
  "portrait_razor_off",
  "portrait_nova_off",
  "portrait_kite_off",
  "portrait_brick_off",
  "portrait_volt_off",
  "ab_razor",
  "ab_nova",
  "ab_kite",
  "ab_brick",
  "ab_volt",
  "ab_razor_off",
  "ab_nova_off",
  "ab_kite_off",
  "ab_brick_off",
  "ab_volt_off",
  "pk_heal",
  "pk_heal_big",
  "pk_teamlife",
  "pk_life",
  "pk_rapid",
  "pk_spread",
  "pk_barrier",
  "e_flyer",
  "pk_ammo",
  "flare",
  "hud_heart",
  "hud_heart_empty",
  "life",
  "hud_skull",
  "hud_crown",
  "dot_0",
  "dot_1",
  "dot_2",
  "dot_3",
  "dot_4",
  "ic_friends",
  "ic_party",
  "ic_queue",
  "ic_invite",
  "ic_settings",
  "ic_admin",
  "ic_bot",
  "ic_key",
  "ic_trophy",
  "ic_exit",
  "fx_storm",
  "fx_tracer",
  "fx_shells",
  "fx_mend",
  "fx_plus",
  "fx_dash",
  "fx_blink",
  "fx_slash",
  "fx_dome",
  "fx_dome_break",
  "fx_arc",
  "fx_spark",
  "fx_charge",
  "bgp_sky_jungle",
  "bgp_sky_base",
  "bgp_far_base",
  "bgp_near_base",
  "bgp_sky_snow",
  "bgp_near_snow",
  "bg15_1",
  "bg15_2",
  "bg15_3",
  "bg15_4",
  "bg15_5",
  "bg15_6",
  "bg15_7",
  "bg15_8",
  "bg15_9",
  "bg15_10",
  "bg15_11",
  "bg15_12",
  "bg15_13",
  "bg15_14",
  "bg15_15",
  "cv50_0",
  "cv50_1",
  "cv50_2",
  "cv50_3",
  "cv50_4",
  "cv50_5",
  "cv50_6",
  "cv50_7",
  "cv50_8",
  "cv50_9",
  "cv50_11",
  "cv50_12",
  "cv50_13",
  "cv50_14",
  "cv50_15",
  "cv50_16",
  "cv50_17",
  "cv50_18",
  "cv50_19",
  "cv50_20",
  "cv50_21",
  "cv50_22",
  "cv50_23",
  "cv50_24",
  "cv50_25",
  "cv50_26",
  "cv50_27",
  "cv50_28",
  "cv50_29",
  "cv50_30",
  "cv50_31",
  "cv50_32",
  "cv50_33",
  "cv50_34",
  "cv50_35",
  "cv50_36",
  "cv50_37",
  "cv50_38",
  "cv50_39",
  "cv50_40",
  "cv50_41",
  "cv50_42",
  "cv50_43",
  "cv50_44",
  "cv50_45",
  "cv50_46",
  "cv50_47",
  "cv50_48",
  "cv50_49",
  "pk_pierce",
  "pk_blast",
  "pk_double",
  "pk_ice",
  "pk_fire",
  "pk_shock",
  "pk_magnet",
  "pk_slowmo",
  "pk_boots",
  "pk_bigheal",
  "ab_ghost",
  "ab_hammer",
  "ab_viper",
  "ab_atlas",
  "pk_autoaim",
  "pk_longer",
  "pk_armor",
  "pk_dcoins",
  "pk_danger"
 ],
 "backgrounds": {
  "jungle": {
   "sky": "bgp_sky_jungle"
  },
  "base": {
   "sky": "bgp_sky_base",
   "far": "bgp_far_base",
   "near": "bgp_near_base"
  },
  "snow": {
   "sky": "bgp_sky_snow",
   "near": "bgp_near_snow"
  }
 },
 "bg15": [
  "bg15_1",
  "bg15_2",
  "bg15_3",
  "bg15_4",
  "bg15_5",
  "bg15_6",
  "bg15_7",
  "bg15_8",
  "bg15_9",
  "bg15_10",
  "bg15_11",
  "bg15_12",
  "bg15_13",
  "bg15_14",
  "bg15_15"
 ],
 "cover50": {
  "jungle": [
   "cv50_0",
   "cv50_1",
   "cv50_4",
   "cv50_5",
   "cv50_6",
   "cv50_13",
   "cv50_15",
   "cv50_16",
   "cv50_14"
  ],
  "base": [
   "cv50_20",
   "cv50_21",
   "cv50_22",
   "cv50_23",
   "cv50_24",
   "cv50_25",
   "cv50_26",
   "cv50_27",
   "cv50_3",
   "cv50_7"
  ],
  "snow": [
   "cv50_30",
   "cv50_31",
   "cv50_32",
   "cv50_33",
   "cv50_34",
   "cv50_35",
   "cv50_36",
   "cv50_37"
  ]
 },
 "idle": {
  "razor": {
   "path": "assets/atlas/idle_razor.png",
   "fw": 224,
   "fh": 378,
   "bh": 378,
   "n": 4,
   "loop": 4
  },
  "nova": {
   "path": "assets/atlas/idle_nova.png",
   "fw": 197,
   "fh": 392,
   "bh": 392,
   "n": 4,
   "loop": 4
  },
  "kite": {
   "path": "assets/atlas/idle_kite.png",
   "fw": 178,
   "fh": 334,
   "bh": 334,
   "n": 4,
   "loop": 4
  },
  "brick": {
   "path": "assets/atlas/idle_brick.png",
   "fw": 236,
   "fh": 363,
   "bh": 363,
   "n": 4,
   "loop": 4
  },
  "volt": {
   "path": "assets/atlas/idle_volt.png",
   "fw": 208,
   "fh": 348,
   "bh": 348,
   "n": 4,
   "loop": 4
  },
  "ghost": {
   "path": "assets/atlas/idle_ghost.png",
   "fw": 180,
   "fh": 290,
   "bh": 290,
   "n": 4,
   "loop": 4
  },
  "hammer": {
   "path": "assets/atlas/idle_hammer.png",
   "fw": 233,
   "fh": 377,
   "bh": 377,
   "n": 4,
   "loop": 4
  },
  "viper": {
   "path": "assets/atlas/idle_viper.png",
   "fw": 200,
   "fh": 367,
   "bh": 367,
   "n": 4,
   "loop": 4
  },
  "atlas": {
   "path": "assets/atlas/idle_atlas.png",
   "fw": 219,
   "fh": 335,
   "bh": 335,
   "n": 4,
   "loop": 4
  },
  "jax": {
   "path": "assets/atlas/idle_jax.png",
   "fw": 231,
   "fh": 427,
   "bh": 427,
   "n": 4,
   "loop": 4
  },
  "duke": {
   "path": "assets/atlas/idle_duke.png",
   "fw": 239,
   "fh": 385,
   "bh": 385,
   "n": 4,
   "loop": 4
  }
 },
 "ui": {
  "fire": "assets/atlas/ui_fire.png",
  "jump": "assets/atlas/ui_jump.png",
  "dash": "assets/atlas/ui_dash.png",
  "skill": "assets/atlas/ui_skill.png",
  "pause": "assets/atlas/ui_pause.png",
  "story": "assets/atlas/ui_story.png",
  "duels": "assets/atlas/ui_duels.png",
  "custom": "assets/atlas/ui_custom.png",
  "crown": "assets/atlas/ui_crown.png",
  "bot": "assets/atlas/ui_bot.png",
  "invite": "assets/atlas/ui_invite.png",
  "coin": "assets/atlas/ui_coin.png",
  "trophy": "assets/atlas/ui_trophy.png",
  "locker": "assets/atlas/ui_locker.png",
  "shop": "assets/atlas/ui_shop.png",
  "friends": "assets/atlas/ui_friends.png",
  "ranks": "assets/atlas/ui_ranks.png",
  "ffa": "assets/atlas/ui_ffa.png",
  "horde": "assets/atlas/ui_horde.png",
  "coop": "assets/atlas/ui_coop.png",
  "hook": "assets/atlas/ui_hook.png",
  "rope": "assets/atlas/ui_rope.png"
 },
 "surf": {
  "g_top_w_jungle": 0.2047,
  "g_top_w_jungle_1": 0.2402,
  "g_top_w_falls": 0.1118,
  "g_top_w_falls_1": 0.1446,
  "g_top_w_base2_1": 0.0068,
  "g_top_w_snow": 0.0263,
  "g_top_w_snow_1": 0.1561,
  "g_top_w_alien": 0.0305,
  "g_top_w_alien_1": 0.0242
 }
};
