// GENERATED by tools/build_art.py — do not edit by hand.
CG.DATA.art = {
 "images": {
  "bullet": "assets/atlas/bullet.png",
  "flash": "assets/atlas/flash.png",
  "pk_rapid": "assets/atlas/pk_rapid.png",
  "pk_barrier": "assets/atlas/pk_barrier.png",
  "pk_life": "assets/atlas/pk_life.png",
  "e_flyer": "assets/atlas/e_flyer.png",
  "e_turret": "assets/atlas/e_turret.png",
  "e_barrel": "assets/atlas/e_barrel.png",
  "e_wreck": "assets/atlas/e_wreck.png",
  "boss_cannon": "assets/atlas/boss_cannon.png",
  "boss_barrel": "assets/atlas/boss_barrel.png",
  "boss_core": "assets/atlas/boss_core.png",
  "boss_core_dmg": "assets/atlas/boss_core_dmg.png",
  "boss_core_dead": "assets/atlas/boss_core_dead.png",
  "ebullet": "assets/atlas/ebullet.png",
  "prop_fern": "assets/atlas/prop_fern.png",
  "prop_rock": "assets/atlas/prop_rock.png",
  "prop_crate": "assets/atlas/prop_crate.png",
  "ledge_jungle": "assets/atlas/ledge_jungle.png",
  "g_top_jungle": "assets/atlas/g_top_jungle.png",
  "g_top_jungle_1": "assets/atlas/g_top_jungle_1.png",
  "g_top_jungle_2": "assets/atlas/g_top_jungle_2.png",
  "g_in_jungle": "assets/atlas/g_in_jungle.png",
  "g_in_jungle_1": "assets/atlas/g_in_jungle_1.png",
  "g_left_jungle": "assets/atlas/g_left_jungle.png",
  "g_right_jungle": "assets/atlas/g_right_jungle.png",
  "water_jungle": "assets/atlas/water_jungle.png",
  "water_deep_jungle": "assets/atlas/water_deep_jungle.png",
  "boss_wall": "assets/atlas/boss_wall.png",
  "g_top_base": "assets/atlas/g_top_base.png",
  "g_top_base_1": "assets/atlas/g_top_base_1.png",
  "g_top_base_2": "assets/atlas/g_top_base_2.png",
  "g_in_base": "assets/atlas/g_in_base.png",
  "g_in_base_1": "assets/atlas/g_in_base_1.png",
  "g_left_base": "assets/atlas/g_left_base.png",
  "g_right_base": "assets/atlas/g_right_base.png",
  "water_base": "assets/atlas/water_base.png",
  "water_deep_base": "assets/atlas/water_deep_base.png",
  "wall_base": "assets/atlas/wall_base.png",
  "g_top_snow": "assets/atlas/g_top_snow.png",
  "g_top_snow_1": "assets/atlas/g_top_snow_1.png",
  "g_top_snow_2": "assets/atlas/g_top_snow_2.png",
  "g_in_snow": "assets/atlas/g_in_snow.png",
  "g_in_snow_1": "assets/atlas/g_in_snow_1.png",
  "water_snow": "assets/atlas/water_snow.png",
  "water_deep_snow": "assets/atlas/water_deep_snow.png",
  "wall_snow": "assets/atlas/wall_snow.png",
  "ledge_base": "assets/atlas/ledge_base.png",
  "ledge_snow": "assets/atlas/ledge_snow.png",
  "prop_11": "assets/atlas/prop_11.png",
  "prop_12": "assets/atlas/prop_12.png",
  "prop_13": "assets/atlas/prop_13.png",
  "prop_14": "assets/atlas/prop_14.png",
  "prop_15": "assets/atlas/prop_15.png",
  "prop_16": "assets/atlas/prop_16.png",
  "prop_17": "assets/atlas/prop_17.png",
  "prop_18": "assets/atlas/prop_18.png",
  "prop_19": "assets/atlas/prop_19.png",
  "prop_31": "assets/atlas/prop_31.png",
  "prop_32": "assets/atlas/prop_32.png",
  "prop_33": "assets/atlas/prop_33.png",
  "prop_34": "assets/atlas/prop_34.png",
  "prop_35": "assets/atlas/prop_35.png",
  "prop_36": "assets/atlas/prop_36.png",
  "prop_37": "assets/atlas/prop_37.png",
  "prop_38": "assets/atlas/prop_38.png",
  "prop_39": "assets/atlas/prop_39.png",
  "prop_40": "assets/atlas/prop_40.png",
  "prop_41": "assets/atlas/prop_41.png",
  "prop_43": "assets/atlas/prop_43.png",
  "prop_45": "assets/atlas/prop_45.png",
  "prop_46": "assets/atlas/prop_46.png",
  "prop_47": "assets/atlas/prop_47.png",
  "prop_48": "assets/atlas/prop_48.png"
 },
 "sheets": {
  "commandos": {
   "path": "assets/atlas/commandos.png",
   "fw": 288,
   "fh": 288
  },
  "sheet_runner": {
   "path": "assets/atlas/sheet_runner.png",
   "fw": 208,
   "fh": 200
  },
  "sheet_rifle": {
   "path": "assets/atlas/sheet_rifle.png",
   "fw": 224,
   "fh": 200
  },
  "fx_boom": {
   "path": "assets/atlas/fx_boom.png",
   "fw": 165,
   "fh": 163
  },
  "fx_splash": {
   "path": "assets/atlas/fx_splash.png",
   "fw": 134,
   "fh": 168
  }
 },
 "scale": {
  "bullet": 0.4554,
  "flash": 0.8824,
  "pk_rapid": 0.6512,
  "pk_barrier": 0.6364,
  "pk_life": 0.8235,
  "e_flyer": 0.75,
  "fx_boom": 0.5818,
  "fx_splash": 1.1194,
  "e_turret": 0.7467,
  "e_barrel": 0.6131,
  "e_wreck": 0.7453,
  "boss_cannon": 0.9667,
  "boss_barrel": 0.7778,
  "boss_core": 0.8516,
  "boss_core_dmg": 0.9041,
  "boss_core_dead": 0.9296,
  "ebullet": 0.7317,
  "prop_fern": 0.7742,
  "prop_rock": 0.6842,
  "prop_crate": 0.6562,
  "prop_11": 0.7285,
  "prop_12": 0.6957,
  "prop_13": 0.7921,
  "prop_14": 0.8982,
  "prop_15": 0.7692,
  "prop_16": 1.2429,
  "prop_17": 0.8889,
  "prop_18": 0.8594,
  "prop_19": 0.7299,
  "prop_31": 1.2258,
  "prop_32": 0.7742,
  "prop_33": 0.7377,
  "prop_34": 0.6944,
  "prop_35": 0.5941,
  "prop_36": 0.8911,
  "prop_37": 1.1043,
  "prop_38": 1.1818,
  "prop_39": 0.8421,
  "prop_40": 1.4208,
  "prop_41": 1.1364,
  "prop_43": 1.4365,
  "prop_45": 0.8434,
  "prop_46": 0.7143,
  "prop_47": 0.6306,
  "prop_48": 0.8805
 },
 "players": [
  {
   "anims": {
    "run_fwd": [
     0,
     5
    ],
    "stand_fwd": [
     6,
     6
    ],
    "stand_up": [
     7,
     7
    ],
    "stand_dup": [
     8,
     8
    ],
    "stand_ddown": [
     9,
     9
    ],
    "run_dup": [
     10,
     12
    ],
    "run_ddown": [
     13,
     14
    ],
    "prone": [
     15,
     15
    ],
    "ball": [
     16,
     17
    ],
    "death": [
     18,
     18
    ]
   },
   "muzzle": {
    "fwd": [
     88,
     -117
    ],
    "up": [
     11,
     -181
    ],
    "dup": [
     81,
     -149
    ],
    "ddown": [
     42,
     -11
    ],
    "prone": [
     115,
     -33
    ]
   }
  },
  {
   "anims": {
    "run_fwd": [
     19,
     24
    ],
    "stand_fwd": [
     25,
     25
    ],
    "stand_up": [
     26,
     26
    ],
    "stand_dup": [
     27,
     27
    ],
    "stand_ddown": [
     28,
     28
    ],
    "run_dup": [
     29,
     31
    ],
    "run_ddown": [
     32,
     33
    ],
    "prone": [
     34,
     34
    ],
    "ball": [
     35,
     36
    ],
    "death": [
     37,
     37
    ]
   },
   "muzzle": {
    "fwd": [
     88,
     -114
    ],
    "up": [
     15,
     -181
    ],
    "dup": [
     80,
     -148
    ],
    "ddown": [
     42,
     -10
    ],
    "prone": [
     113,
     -34
    ]
   }
  }
 ],
 "originY": 0.8333333333333334,
 "playerScale": 0.825,
 "enemyScale": 0.8627,
 "props": {
  "jungle": [
   "prop_fern",
   "prop_rock",
   "prop_crate",
   "prop_40",
   "prop_41",
   "prop_43",
   "prop_45",
   "prop_46",
   "prop_47",
   "prop_48"
  ],
  "base": [
   "prop_11",
   "prop_12",
   "prop_13",
   "prop_14",
   "prop_15",
   "prop_16",
   "prop_17",
   "prop_18",
   "prop_19"
  ],
  "snow": [
   "prop_31",
   "prop_32",
   "prop_33",
   "prop_34",
   "prop_35",
   "prop_36",
   "prop_37",
   "prop_38",
   "prop_39"
  ]
 }
};
