// GENERATED by tools/build_art.py — do not edit by hand.
CG.DATA.art = {
 "images": {
  "bullet": "assets/atlas/bullet.png",
  "flash": "assets/atlas/flash.png",
  "pk_rapid": "assets/atlas/pk_rapid.png",
  "pk_barrier": "assets/atlas/pk_barrier.png",
  "pk_life": "assets/atlas/pk_life.png",
  "e_flyer": "assets/atlas/e_flyer.png"
 },
 "sheets": {
  "commandos": {
   "path": "assets/atlas/commandos.png",
   "fw": 288,
   "fh": 288
  }
 },
 "scale": {
  "bullet": 0.4554,
  "flash": 0.8824,
  "pk_rapid": 0.6512,
  "pk_barrier": 0.6364,
  "pk_life": 0.8235,
  "e_flyer": 0.75
 },
 "players": [
  {
   "anims": {
    "run_fwd": [
     0,
     5
    ],
    "stand_fwd": [
     6,
     6
    ],
    "stand_up": [
     7,
     7
    ],
    "stand_dup": [
     8,
     8
    ],
    "stand_ddown": [
     9,
     9
    ],
    "run_dup": [
     10,
     12
    ],
    "run_ddown": [
     13,
     14
    ],
    "prone": [
     15,
     15
    ],
    "ball": [
     16,
     17
    ],
    "death": [
     18,
     18
    ]
   },
   "muzzle": {
    "fwd": [
     88,
     -117
    ],
    "up": [
     11,
     -181
    ],
    "dup": [
     81,
     -149
    ],
    "ddown": [
     42,
     -11
    ],
    "prone": [
     115,
     -33
    ]
   }
  },
  {
   "anims": {
    "run_fwd": [
     19,
     24
    ],
    "stand_fwd": [
     25,
     25
    ],
    "stand_up": [
     26,
     26
    ],
    "stand_dup": [
     27,
     27
    ],
    "stand_ddown": [
     28,
     28
    ],
    "run_dup": [
     29,
     31
    ],
    "run_ddown": [
     32,
     33
    ],
    "prone": [
     34,
     34
    ],
    "ball": [
     35,
     36
    ],
    "death": [
     37,
     37
    ]
   },
   "muzzle": {
    "fwd": [
     88,
     -114
    ],
    "up": [
     15,
     -181
    ],
    "dup": [
     80,
     -148
    ],
    "ddown": [
     42,
     -10
    ],
    "prone": [
     113,
     -34
    ]
   }
  }
 ],
 "originY": 0.8333333333333334,
 "playerScale": 0.825
};
